---
title: "AMA Lab 5"
author: "Cecilia, Rudio, Gerard"
date: "2023-11-18"
output: html_document
---

```{r}
library(sm)
countries<-read.csv2(file="HDI.2017.subset.csv",row.names = 1)
attach(countries)
ind.agr<-(Agric.employ.. < median(Agric.employ..) )

```


## Bandwidth choice for the local Poisson regression

```{r}
h.cv.sm.poisson <- function(x,y,rg.h=NULL,l.h=10,method=loo.cv){
   cv.h <- numeric(l.h)
   if (is.null(rg.h)){
      hh <- c(h.select(x,y,method="cv"),
              h.select(x,y,method="aicc"))#,hcv(x,y))
      rg.h <- range(hh)*c(1/1.1, 1.5)
   }
   i <- 0
   gr.h <- exp( seq(log(rg.h[1]), log(rg.h[2]), l=l.h))
   for (h in gr.h){
      i <- i+1
      cv.h[i] <- method(x,y,h)
   }
   return(list(h = gr.h, 
               cv.h = cv.h,
               h.cv = gr.h[which.min(cv.h)]))
}

loo.cv <- function(x,y,h){
  n <- length(x)
  pred <- sapply(1:n, 
      function(i,x,y,h){
         sm.poisson(x=x[-i],y=y[-i],h=h,eval.points=x[i],display="none")$estimate
      },   x,y,h)
  return(1/n * sum(log(pred)))
}
```



# Local Poisson regression for Country Development Data

```{r}
le.fm.r <- round(le.fm)

h.CV.loglik <- h.cv.sm.poisson(Life.expec,le.fm.r,method=loo.cv)
plot(h.CV.loglik$h,h.CV.loglik$cv.h)
lines(h.CV.loglik$h,h.CV.loglik$cv.h)
```
```{r}
aux <- sm.poisson(Life.expec,le.fm.r,h=h.CV.loglik$h.cv)
title(main=paste("h.cv.loglik =",round(h.CV.loglik$h.cv,2),sep=""))
```

